name: Metacoder
theme: flatly
use_dir_names: no
use_file_names: yes
use_file_suffix: yes
name_sep: "--"
partial_copy: no
menu_name_parser: !expr function(x) gsub('^[0-9]*_', '', x)
type: Rmd
placement:
- index.Rmd:
  - ""
- '*_*':
  - Vignettes
  - .